  - name: To execute a command
    command: hostname -s
    notify: Print command message
  - name: Install apache on webserver
    package: name={{pkg_name}} state={{pkg_state}}
  - name: Start apache Server
    service: name={{pkg_name}} state=started
  - name: Deploy html page on apache
    template: src=index.html.j2 dest=/var/www/html/index.html
    notify: Restart the apache2 server
